CREATE TABLE `pvuv_sink` (
	`id` BIGINT(19) NOT NULL AUTO_INCREMENT,
	`dt` DATETIME NOT NULL,
	`pv` BIGINT(19) NOT NULL,
	`uv` BIGINT(19) NOT NULL,
	`updateTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (`id`) USING BTREE,
	UNIQUE INDEX `idx_dt` (`dt`) USING BTREE
)
COLLATE='utf8mb4_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=1000006222
;
